
[versions]
unimined = "1.3.14"
kotlin = "2.2.21"
shaddow = "9.2.2"
detekt = "1.23.8"
mixins = "0.8.5"
weblite = "1.2"

[libraries]
kotlin-stllib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref="kotlin" }
mixins = { module = "org.spongepowered:mixin", version.ref = "mixins" }
weblite = { module = "ca.weblite:java-objc-bridge", version.ref = "weblite"}
#junit = {}

[plugins]
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
shaddow = { id = "com.gradleup.shadow", version.ref = "shaddow" }
